apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-system
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform

  source:
    repoURL: https://github.com/bl-solutions/lab-argocd.git
    targetRevision: HEAD
    path: example/platform/crossplane

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    retry:
      limit: 0
    automated:
      prune: true
      selfHeal: true
